/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ss.task;

import org.junit.Test;

import static org.junit.Assert.assertNotNull;

public class AppTest {

    @Test
    public void testAppHasAGreeting() {
        assertNotNull("app should have a greeting", "");
    }
}
