/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ss.task;

import com.ss.task.services.BitcoinService;

public class App {

    public static void main(String[] args) {

        BitcoinService service = new BitcoinService();
        service.startProcess();
    }
}

